// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"context"
	"github.com/urfave/cli/v3"
	"sn/api"
	"sn/api/rest/handlers"
	"sn/internal/repository/user"
	"sn/internal/service"
)

// Injectors from wire.go:

func InitializeApplication(c *cli.Command, appCtx context.Context) (api.Container, error) {
	client, err := providePostgresClient(appCtx, c)
	if err != nil {
		return api.Container{}, err
	}
	userStore := repository.NewStore(client)
	userService := service.NewService(userStore)
	resolver := handlers.NewResolver(userService)
	serverConfig, err := provideRestServerConfig(appCtx, c)
	if err != nil {
		return api.Container{}, err
	}
	server := handlers.NewServer(resolver, serverConfig)
	container := api.NewContainer(client, server)
	return container, nil
}
